with rm as (

    SELECT 
    LISTING_ID, 
    CHANGE_DATE,
    UPPER(TRIM(replace(REPLACE(CONCAT(ADDRESS_1::VARCHAR,ADDRESS_2::VARCHAR),' '),','))) AS ADDRESSID, 
    ADDRESS_1,
    ADDRESS_2,
    FULL_POSTCODE, 
    UPRN,
    LOCAL_AUTHORITY_CODE,
    LOCAL_AUTHORITY,
    GOV_REGION_CODE,
    FLOOR_AREA,
    FLOOR_LEVEL,
    BEDROOM,
    PROPERTY_TYPE_1,
    PROPERTY_TYPE_2,
    COMBINED_PROPERTY_TYPE,
    BRANCH_ID,
	 BRANCH_NAME,
    WEBSITE_URL,
	 COMPANY_NAME
    FROM 
       {{ source('RIGHTMOVE_PROD', 'CLEAN_RAW_RIGHTMOVE_DATA') }} 

 
)

SELECT * FROM rm